[features]
seeds = false
skip-lint = false
[programs.localnet]
rock_destroyer = "BPTPw1pRW4uHPRtHMzscDQiLGQqLr4Qj12UFwCGG1ijq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/workspace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
