[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rock_destroyer = "RoCK6dTHRi3EvCQx4zJRRBDKNy2FDeqcj1m4sb7sn7a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "game-owner.json"

[scripts]
test = "bun test --timeout 1000000"
